server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  jpa:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver